import exp from "constants";

export type Web3event = {
    id: number,
    start_time: string,
    end_time: string,
    register_type: number,
    image: string,
    title: string,
    organizer: string,
    addr: string,
    click_num: number,
    is_collect: number,
    is_like: number
};

export type Web3eventDetail = {
    id: number,
    type: number,
    topics: string[],
    topics_name: string[],
    categories: string[],
    categories_name: string[],
    start_time: string,
    end_time: string,
    place: number,
    register_type: number,
    locale: string,
    image: string,
    title: string,
    source_url: string,
    organizer: string,
    description: string,
    timezone: string,
    pay: number,
    lat: number,
    lon: number,
    is_visible: number,
    user_id: number,
    addr: string,
    click_num: number,
    is_collect: number,
    is_like: number,
    code: string,
    event_url: string,
    format: number,
    capacity: number,
    is_place: number,
    manager: {
        id: number,
        avatar: string,
        nickname: string,
        is_follow: false,
        status: number,
        follower_count: number,
        following_count: number,
        event_count: number
    },
    speakers: string[],
    hosts: string[],
    organizations: string[],
    participant: {
        list: string[],
        total: number
    },
    event_tickets: any[],
    my_ticket: any[],
    is_check_in: boolean
};

export type Web3eventDescription = {
    summary: string,
    content: {
        admat: any,
        hasAutoGeneratedContent: boolean,
        modules:Web3eventModule[],
        widgets: any[],
    }
};

export type Web3eventModule = {
    alignment: string,
    text: string,
    type: string
}